dist: trusty # use the newer operating system
sudo: false # run our builds in containers
language: go
go:
- 1.12.x
env:
  - GO111MODULE=on
install: true
stages:
- name: Testing
- name: Build
jobs:
  include:
  - stage: Testing
    name: Testing
    script:
    - make
  - stage: Build
    name: Build
    script:
    - make build
